version: '3.5'

services:

    tailscale:
        image: jonoh/tailscale:1.12.3
        restart: always
        volumes:
            - ./data/tailscale:/var/lib/tailscale
        devices:
            - /dev/net/tun:/dev/net/tun
        network_mode: host
        privileged: true
        environment:
            - AUTH_KEY=${TAILSCALE_AUTH_KEY}
        command: --advertise-exit-node --advertise-routes=10.0.8.0/24 --hostname=pi

    socks_proxy:
        image: jonoh/socks:1.4.2
        restart: always
        ports:
            - 1080:1080

    homebridge:
        image: jonoh/homebridge:1.3.4
        restart: always
        network_mode: host
        environment:
            - TZ=Pacific/Auckland
            - PGID=1000
            - PUID=1000
            - HOMEBRIDGE_CONFIG_UI=1
            - HOMEBRIDGE_INSECURE=1
            - HOMEBRIDGE_CONFIG_UI_PORT=8581
        volumes:
            - ./data/homebridge:/homebridge

    cloudflare_homebridge:
        image: jonoh/cloudflared:2021.8.2
        restart: always
        network_mode: host
        volumes:
            - ./data/cloudflare_homebridge:/config
        environment:
            - TZ=Pacific/Auckland
            - TUNNEL_URL=http://localhost:10380
            - ACCOUNT_ID=${CF_ACCOUNT_ID}
            - TUNNEL_NAME=homebridge
            - TUNNEL_ID=${HOMEBRIDGE_TUNNEL_ID}
            - TUNNEL_SECRET=${HOMEBRIDGE_TUNNEL_SECRET}

    rclone_serve_backup:
        image: rclone/rclone:1.56.0
        restart: always
        entrypoint: nice
        command: >
            -n 10 rclone
            serve sftp
            --addr :2022
            --authorized-keys /config/authorized_keys
            jotta-raw:/backup
        volumes:
            - ./data/rclone_serve_backup:/config

    # duplicacy_root:
    #     image: jonoh/duplicacy:2.7.2
    #     restart: always
    #     environment:
    #         - BACKUP_CRON=0 * * * *
    #         - PRUNE_CRON=34 1 * * sun
    #         - RUN_JOB_IMMEDIATELY=yes
    #         - SNAPSHOT_ID=nas_root
    #         - STORAGE_URL=/storage
    #         - JOB_RANDOM_DELAY=30
    #         - PRUNE_KEEP_POLICIES=0:360;30:180;7:30;1:7
    #         - FILTER_PATTERNS=-naspool/;-sys/;-dev/;-var/lib/
    #     volumes:
    #         - /:/data:ro
    #         - ./data/duplicacy_root:/config
    #         - /naspool/Backups/root:/storage

    duplicacy_naspool:
        image: jonoh/duplicacy:2.7.2
        restart: always
        environment:
            # - BACKUP_CRON=1 1 * * *
            # - RUN_JOB_IMMEDIATELY=yes
            - PRUNE_CON=5 3 * * sun
            - SNAPSHOT_ID=naspool
            - DUPLICACY_SSH_KEY_FILE=/config/ssh_key
            - DUPLICACY_PASSWORD=${DUPLICACY_PASSWORD}
            - STORAGE_URL=sftp://rclone_serve_backup:2022//duplicacy
            - JOB_RANDOM_DELAY=300
            - PRUNE_KEEP_POLICIES=0:360;30:180;7:30;1:7
            - PRE_BACKUP_SCRIPT=/usr/local/bin/pre_backup.sh
        volumes:
            - /naspool:/data
            - ./data/duplicacy_naspool:/config
            - ./config/duplicacy_naspool/pre_backup.sh:/usr/local/bin/pre_backup.sh

    sponsorblockcast:
        image: erdnaxeli/castblock:latest
        restart: always
        network_mode: host
        cap_add: 
            - NET_ADMIN
        command: --mute-ads

    tvheadend:
        image: linuxserver/tvheadend
        container_name: tvheadend
        restart: always    
        labels:
            - autoheal=true
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Pacific/Auckland
        volumes:
            - ./data/tvheadend:/config
        ports:
            - 9981:9981
        healthcheck:
            test: curl -f https://tvheadend.hillnz.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 1
            start_period: 30s

    cloudflare_tvheadend:
        image: jonoh/cloudflared:2022.2.1
        restart: always
        volumes:
            - ./data/cloudflare_tvheadend:/config
        environment:
            - TZ=Pacific/Auckland
            - TUNNEL_URL=http://tvheadend:9981
            - ACCOUNT_ID=${CF_ACCOUNT_ID}
            - TUNNEL_NAME=tvheadend
            - TUNNEL_ID=${TV_TUNNEL_ID}
            - TUNNEL_SECRET=${TV_TUNNEL_SECRET}

    background_encode:
        image: background_encode
        restart: always
        volumes:
            - /pool/convert:/convert
            - /home/ubuntu/.config/rclone:/home/abc/.config/rclone
        environment:
            - ENCODE_VIDEO_DIR=jotta:/plex-media
            - ENCODE_BUFFER_SIZE=20
            - ENCODE_TRANSCODER=noop
